export const notificationType = {
    CART_REMINDER: "CART_REMINDER",
    PROFILE_UPDATE: "ACCOUNT_UPDATE",
    BOOK_BACK_IN_STOCK: "BOOK_BACK_IN_STOCK",
    PRICE_DROP: "PRICE_DROP",
    NEW_EDITION: "NEW_EDITION",
    ORDER_CONFIRMED: "ORDER_CONFIRMATION",
    ORDER_PROCESSING: "ORDER_PROCESSING",
    ORDER_SHIPPED: "ORDER_SHIPPED",
    ORDER_DELIVERED: "ORDER_DELIVERED",
    ORDER_CANCELLED: "ORDER_CANCELLED",
    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
};
export const notificationPriority = {
    LOW: "low",
    MEDIUM: "medium",
    HIGH: "high",
    URGENT: "urgent",
};
